spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:///D:/backend/git/springcloud-demo/config-server-demo/src/main/resources/config
#            - file:///F:/dir/config-repos/mrcode/zirr

server:
  port: 8088


